kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: 'k3d-registry:38597/nodejs'
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MYSQL_HOST
              value: mariadb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: db
